info:
  app:
    name: pf-auth-server
    description: Authentication Service
    version: ${project.parent.version}

management:
    endpoints:
      web:
        base-path:
        exposure.include: "*"
      metrics.enabled: true
      info.enabled: true
      health.enabled: true
    metrics:
      export:
        cloudwatch:
          namespace: pf-auth-server-metrics
          batchSize: 20

spring:
  application:
    name: auth-service
  kafka:
    bootstrap-servers: kafka-3a84ca08-paulo-415b.aivencloud.com:26668
    properties:
      specific.avro.reader: true
      request.timeout.ms: 60000
      linger.ms: 0
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="avnadmin" password="yjxekdzm5ce12r6m";
    specific.avro.reader: true
    ssl:
      truststore-location: file:/tmp/client.truststore.jks
      truststore-password: msc74kuy1hdugrif
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        schema.registry.url: http://localhost:8081
      retries: 3
      acks: 1
      batch-size: 0
      ack-timeout-secs: 60
      buffer-memory: 200

kafka:
  topicName: poc

server:
  port: 9100

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 600
    secret: JwtSecretKey
    refresh.expiration: 3600



mongodb:
  host: 0.0.0.0
  database:
    name: pf-auth

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

cloud:
  aws:
    credentials:
      instanceProfile: true
    region.static: us-east-1
    stack.auto: false

