apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pf-auth-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pf-auth-server
    spec:
      containers:
        - name: pf-auth-server
          image: pfernand/pf-auth-server
          env:
            - name: ENDPOINT
              value: "https://secretsmanager.us-east-1.amazonaws.com"
            - name: REGION
              value: "us-east-1"
            - name:
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred